language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.1.6
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - rbx-2
  - jruby-head
  - ruby-head
before_install: gem install bundler -v 1.10.5
